# Generated by Django 2.0.6 on 2019-03-01 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateofwork', models.DateField(max_length=20)),
                ('dateofentry', models.DateTimeField(default=datetime.datetime(2019, 3, 1, 16, 27, 40, 235125, tzinfo=utc))),
            ],
        ),
    ]
