# Generated by Django 2.0.6 on 2019-03-01 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='dateofentry',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 16, 30, 5, 929203, tzinfo=utc)),
        ),
    ]
